name: goreleaser

on: [push,pull_request]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      -
        name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      -
        name: Run Script
        run:
          .github/workflows/build/build.bat ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tmp/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}