name: goreleaser

on: [push,pull_request]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      -
        name: Run Tet
        if: "!startsWith(github.ref, 'refs/tags/')"
        run:
          .github/workflows/build/test.bat
      -
        name: Run Script
        if: startsWith(github.ref, 'refs/tags/')
        run:
          .github/workflows/build/build.bat

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tmp/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}